// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DatatablesController from "./datatables_controller"
application.register("datatables", DatatablesController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import NestedFormController from "./nested_form_controller"
application.register("nested-form", NestedFormController)

import SelectController from "./ts/select_controller"
application.register("select", SelectController)

import ShowSecretController from "./show_secret_controller"
application.register("show-secret", ShowSecretController)

import SortableController from "./sortable_controller"
application.register("sortable", SortableController)

import TaggingController from "./tagging_controller"
application.register("tagging", TaggingController)

import ToastController from "./toast_controller"
application.register("toast", ToastController)

import ToggleFieldsController from "./toggle_fields_controller"
application.register("toggle-fields", ToggleFieldsController)

import PolymorphicSelectController from "@swobspace/stimulus-polymorphic-select"
application.register("polymorphic-select", PolymorphicSelectController)

import PopoverController from "./popover_controller"
application.register("popover", PopoverController)

import TooltipController from "./tooltip_controller"
application.register("tooltip", TooltipController)

