// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DatatablesController from "./datatables_controller"
application.register("datatables", DatatablesController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import NestedFormController from "./nested_form_controller"
application.register("nested-form", NestedFormController)

import SelectController from "./ts/select_controller"
application.register("select", SelectController)

import SortableController from "./sortable_controller.js"
application.register("sortable", SortableController)

import ToastController from "./toast_controller"
application.register("toast", ToastController)

import PolymorphicSelectController from "@swobspace/stimulus-polymorphic-select"
application.register("polymorphic-select", PolymorphicSelectController)
