@startuml

state OK #lightgreen
OK: Card online;
OK: SMC-B PIN verifiziert für alle Kontexte;
OK: Zertifikat gültig > 3 Monate;

state WARNING #Yellow
WARNING: Zertifikat gültig, <= 3 Monate;

state CRITICAL #orangered
CRITICAL: Zertifikat abgelaufen;
CRITICAL: SMC-B PIN nicht verifiziert\n(über alle Kontexte);

state UNKNOWN #LightSkyBlue
UNKNOWN: SMC-B: Zertifikat nicht eingelesen;

state NOTHING #LightGrey
NOTHING: Connector oder CardTerminal nicht zugewiesen;
NOTHING: SMC-B Context nicht zugewiesen;
NOTHING: Karte nicht in Betrieb;
NOTHING: Kein Ablaufdatum erfasst;

NOTHING --> UNKNOWN
UNKNOWN --> CRITICAL
CRITICAL --> WARNING
WARNING --> OK
@enduml