@startuml
top to bottom direction

!theme cocard from .

class Connector  {
  name: string
  description: rich_text
  ip: inet
  sds_url: string
  manual_update: boolean
  --
  sds_xml: text
  sds_updated_at: timestamp
  connector_services: jsonb
  last_check: timestamp
  last_check_ok: timestamp
  condition: integer
  soap_request_success: boolean
  vpnti_online: boolean
}

class CardTerminal {
  displayname: string
  description: rich_text
  room: string
  contact: string
  plugged_in: string
  location_id
  --
  properties: jsonb
  name: string
  ct_id: string
  mac: macaddr
  ip: inet
  slots: integer
  connected: boolean
  condition: integer
  connector_id
}

class Location {
  lid: string
  description: string
}

class Context {
  mandant: string
  client_system: string
  workplace: string
  description: string
}

class ConnectorContext {
  connector_id
  context_id
  position: integer
}

class Card {
  name: string
  description: rich_text
  --
  properties: jsonb
  card_handle: string
  card_type: string
  iccsn: string
  slotid: integer
  insert_time: timestamp
  card_holder_name: string
  expiration_date: date
  card_terminal_id
}

class Workplace {
  description: string
  --
  name: string
}
Class TerminalWorkplaces {
  card_terminal_id
  workplace_id
  updated_at
}

Location "*" -- "*" Connector
Context "*" -- "*" Connector
Connector "1" - "*" CardTerminal
Location "1" - "*" CardTerminal
(Connector, Context) .. ConnectorContext
CardTerminal "1" - "*" Card
CardTerminal "*" -- "*" Workplace
(CardTerminal, Workplace) .. TerminalWorkplaces
@enduml
