@startuml
top to bottom direction

!theme cocard from .

class Connector  {
  name: string
  description: rich_text
  ip: inet
  sds_url: string
  manual_update: boolean
  --
  sds_xml: text
  sds_updated_at: timestamp
  connector_services: jsonb
  last_check: timestamp
  last_check_ok: timestamp
  condition: integer
}

class Location {
  lid: string
  description: string
}

class Context {
  mandant: string
  client_system: string
  workplace: string
  description: string
}

Location "*" -- "*" Connector
Context "*" -- "*" Connector

@enduml
