= Erweiterte Konfiguration
:author: Wolfgang Barth
:revdate: 2025-12-25


Die erweiterte Konfiguration über die Konfigurationsdatei `cocard.yml` ist komplett optional. Die Datei wird nur benötigt, wenn Konfiguration für eine der hier beschriebenen Funktionen erforderlich ist. Andernfalls kann die Datei komplett entfallen.


== Die Konfigurationsdatei `cocard.yml`

=== LDAP-Anbindung

.cocard.yml: LDAP-Anbindung
[source,yml]
----
enable_ldap_authentication: true
ldap_options:
[...]
----

Die LDAP-Anbindung wird im Detail unter xref:ROOT:admin/ldap-authentication.adoc[] beschrieben

=== TI-Client (RISE TI-Gateway)

.cocard.yml: TI-Client (RISE TI-Gateway)
[source,yml]
----
enable_ticlient: yes
ktproxy_equal_ports: yes
ktproxy_defaults:
  wireguard_ip: 203.0.113.0
  incoming_ip: 198.51.100.20
  incoming_port_range: 10000:11000
  outgoing_ip: 198.51.100.21
  outgoing_port_range: 10000:11000
  card_terminal_port: 4742
----

=== Kartenterminals: Defaultwerte

Folgende Default-Werte sind derzeit konfigurierbar:

.cocard.yml: Default-Werte für Kartenterminals
[source,yml]
----
card_terminal_defaults:
  ntp_enabled: true
  ntp_server: 198.51.100.1
  tftp_server: 198.51.100.50
  tftp_file: mctfirmware.dfu
  dhcp_enabled: true
  remote_pin_enabled: true
  remote_pairing_enabled: true
  firmware_version: 3.9.2
----

=== Mailversand

.cocard.yml: Settings für Mailversand
[source,yml]
----
smtp_settings:
  address: myhost.example.com
  port: 25
  domain: example.com
  enable_starttls_auto: false
----

Der Mailversand erfolgt ausschließlich via SMTP. Eine Beschreibung möglicher Konfigurationen siehe link:https://guides.rubyonrails.org/v7.2/action_mailer_basics.html#example-action-mailer-configuration[Rails Guides: Action Mailer Basics].

NOTE:: Ein einfaches Setup wäre, wenn man den Host, auf dem Cocard läuft, für SMTP-Empfang und Versand konfiguriert und Cocard dann über `address` einfach die öffentliche IP oder FQDN des Hosts übergibt. Dann kann man die sichere Konfiguration am Host selbst vornehmen und auf Authentifikation bei Versand aus einem lokalen Container heraus ggf. verzichten.
