= Konfiguration
:author: Wolfgang Barth
:revdate: 2024-08-11

NOTE: Die gesamte externe Konfiguration findet zum jetzigen Zeitpunkt als Umgebungsvariablen noch in `env.production` statt. In einer späteren Version werden ggf. einige Variablen in eine externe Konfigurationsdatei ausgelagert.

.env.production
[source,toml]
----
# -------------------------------------------------------------------
# WICHTIG: alle Passwörter unten vor Inbetriebnahme ändern!
# -> SECRET_KEY_BASE, POSTGRES_PASSWORD
# -------------------------------------------------------------------
#
# Timezone, Locale
TZ=Europe/Berlin
LOCALE=de

# generate key with bin/rails secret
# head -c64 </dev/urandom | xxd -p -c 64
SECRET_KEY_BASE=7eedef6a36b8c32a4a60c3c49567ac7469e5724fe1755177d41697917b1c0ca46e00b81c28a51593e3c04ea5aa874fac4c2e4ea0650902246c71c03461dcb4df

# -- redis
REDIS_URL=redis://cocard-redis:6379

# -- postgres
POSTGRES_DB=cocard_production
POSTGRES_USER=cocard
# pwgen 31 1
POSTGRES_PASSWORD=eithaeshaeQu6ohsidaiNgaingaequi
POSTGRES_HOST=cocard-postgres

# URL building
URL_HOST=cocard.example.com
URL_PORT=8443
URL_PROTOCOL=https
----

[cols="1m,4"]
|===
|Variable | Beschreibung

|TZ
|Zeitzone, z.B. `Europe/Berlin`

|LOCALE
|

|SECRET_KEY_BASE
|Basis-Secret für Rails für die Absicherung von Sessions.

|REDIS_URL
|URL für den Zugriff auf den Redis-Container; Zugriff erfolgt über das interne Cocard-Netzwerk und benötigt daher den Hostnamen des Redis-Containers.

|POSTGRES_DB
|Name der PostgreSQL-Datenbank-Instanz

|POSTGRES_USER
|Benutzer für PostgreSQL

|POSTGRES_PASSWORD
|Passwort

|POSTGRES_HOST
|Hostname aus Sicht des Cocard-Containers in Cocard-Netzwerk.

|URL_HOST
|Hostname, unter der Cocard von außen erreichbar ist

|URL_PORT
|Port, über den Cocard von außen erreichbar ist. Entweder 3000 bei direkter Veröffentlichung des Cocard-Ports oder 8443 via Traefik, wenn die Beispielkonfiguration verwendet wird.

|URL_PROTOCOL
|Protokoll für den Zugriff (http bei direktem Zugriff)
|===