= Installation
:revdate: 2024-08-09
:author: Wolfgang Barth

== Podman

Ich benutze `podman` anstelle von `docker`. `podman` integriert sich mit Quadlets bestens in `systemd`, und das auch noch als normaler Benutzer (rootless). Wer sich mit `docker` und `docker-compose` wohler fühlt, sollte einen Blick auf das Create-Skript für den Quickstart werfen: xref:attachment$quickstart/create-playground.sh[create-playground.sh]. Mit etwas Docker-Erfahrung sollte sich das Skript einfach in ein `docker-compose.yml` verwandeln lassen.


== xref:podman/quickstart.adoc[]

Im Quickstart-Guide kommt `podman pod` zum Einsatz. Die Umgebung ist nicht für den produktiven Einsatz gedacht, ist aber einfach anzuwenden, wenn man Cocard einfach mal nur ausprobieren will.

== xref:podman/podman-systemd.adoc[]

Quadlets integrieren sich perfekt in `systemd` und sind daher die bevorzugte Variante für den produktiven Einsatz von Podman. Benötigt wird mindestens `podman` Version 4.4.

== xref:podman/reverse-proxy.adoc[]

Cocard als Container ist für den Einsatz hinter einen Reverse Proxy wie Traefik gedacht. Der Einsatz mit Apache2 oder Nginx ist aber ebenfalls möglich. Cocard stellt selbst keine TLS-Verbindung zur Verfügung, die Handhabung von TLS und den notwendigen Zertifikaten ist Aufgabe des Reverse Proxy.