= Modeling cocard
:author: Wolfgang Barth
:revdate: 2024-05-19
:imagesdir: ../images

== Overall Picture

image::models.svg[]

== Home controller

[source,sh]
----
bin/rails g controller Home index \
  --no-stylesheets --no-javascripts --no-helper
----

== model Location

[source,sh]
----
bin/rails g scaffold Location \
  lid:string \
  description:string \
  --no-stylesheets --no-javascripts --no-helper
----

i.e. `NRH`, `BNA`. Only for grouping and information.

== model Context

Context for SOAP requests.

[source,sh]
----
bin/rails g scaffold Context \
  mandant:string \
  client_system:string \
  workplace:string \
  description:string \
  --no-stylesheets --no-javascripts --no-helper
----

i.e. `ORBIS`, `Ein1`. Used as `Mandant_id` in SOAP requests.

== model Connector

[source,sh]
----
bin/rails g scaffold Connector \
  name:string \
  ip:inet \
  admin_url:string \
  sds_url:string \
  manual_update:boolean \
    --no-stylesheets --no-javascripts --no-helper

bin/rails g migration AddReadonlyToConnector \
  sds_xml:text \
  sds_updated_at: \
  connector_services:jsonb \
  last_check:timestamp last_check_ok:timestamp \
  condition:integer:index \
  soap_request_success:boolean \
  vpnti_online:boolean \
  firmware_version:string
----

.Install ActionText
[source,sh]
----
bin/rails action_text:install
----

.app/models/connector.rb
[source,ruby]
----
class Connector < ApplicationRecord
  has_rich_text :description
end
----

== model CardTerminal

[source,sh]
----
bin/rails g scaffold CardTerminal \
  displayname:string \
  location:belongs_to \
  room:string \
  contact:string \
  plugged_in:string \
  delivery_date:date \
  supplier:string \
  serial:string \
  id_product:string \
  --no-stylesheets --no-javascripts --no-helper

bin/rails g migration AddInternalToCardTerminal \
  properties:jsonb \
  name:string \
  ct_id:string \
  mac:macaddr \
  ip:inet \
  slots:integer \
  connected:boolean \
  condition:integer \
  connector:belongs_to \
  firmware_version:string
----


.app/models/card_terminal.rb
[source,ruby]
----
class CardTerminal < ApplicationRecord
  has_rich_text :description
end
----

== model Card

[source,sh]
----
bin/rails g scaffold Card \
  name:string \
  operational_state:belongs_to \
  location:belongs_to \
  lanr:string \
  bsnr:string \
  fachrichtung:string \
  telematikid:string \
  context:belongs_to \
  private_information:rich_text \
    --no-stylesheets --no-javascripts --no-helper

bin/rails g migration AddInternalToCard \
  properties:jsonb \
  card_handle:string \
  card_type:string \
  iccsn:string \
  slotid:integer \
  insert_time:timestamp \
  card_holder_name:string \
  expiration_date:date \
  condition:integer \
  pin_status:string \
  card_terminal:belongs_to

bin/rails g migration AddCertificateToCard \
  certificate:text \
  cert_subject_cn:string \
  cert_subject_title:string \
  cert_subject_sn:string \
  cert_subject_givenname:string \
  cert_subject_street:string \
  cert_subject_postalcode:string \
  cert_subject_l:string \
  cert_subject_o:string
----

.app/models/card_terminal.rb
[source,ruby]
----
class Card < ApplicationRecord
  has_rich_text :description
end
----

== model OperationalState

[source,sh]
----
bin/rails g scaffold OperationalState \
  name:string \
  description:string \
  operational:boolean:index \
  --no-stylesheets --no-javascripts --no-helper
----

== model Log

[source,sh]
----
bin/rails g scaffold Log \
  loggable:references{polymorphic} \
  action:string \
  last_seen:timestamp \
  level:string:index \
  message:text \
  is_valid:boolean \
  condition:integer \
  --no-stylesheets --no-javascripts --no-helper
----

== model Network

[source,sh]
----
bin/rails g scaffold Network \
  netzwerk:cidr \
  description:rich_text \
  location:belongs_to \
  --no-stylesheets --no-javascripts --no-helper
----

== model Workplace

[source,sh]
----
bin/rails g scaffold Workplace \
  description:rich_text
  --no-stylesheets --no-javascripts --no-helper

bin/rails g migration AddNameToWorkplace \
  name:string
----

== HABTM Tables

.Join Tables for HABTM
[source,sh]
----
bin/rails g migration CreateJoinTableConnectorLocation \
  connector location
----

Add index and set index to unique:

[source,ruby]
----
class CreateJoinTableConnectorLocation < ActiveRecord::Migration[7.1]
  def change
    create_join_table :connectors, :locations do |t|
      t.index [:location_id, :connector_id], unique: true
      t.index [:connector_id, :location_id], unique: true
    end
  end
end
----

== HABTM Connector -- Context through ConnectorContext

HABTM for Connector and Context with additional attributes

[source,sh]
----
bin/rails g model ConnectorContext \
  connector:belongs_to \
  context:belongs_to \
  position:integer:index \
  --no-stylesheets --no-javascripts --no-helper
----

.Unique Index for ConnectorContext
[source,ruby]
----
t.index [:connector_id, :context_id], unique: true
t.index [:context_id, :connector_id], unique: true
----

== HABTM Terminal -- Workplaces through TerminalWorkplaces

HABTM for Terminals and Workplaces with additional attributes

[source,sh]
----
bin/rails g model TerminalWorkplaces \
  card_terminal:belongs_to \
  workplace:belongs_to \
  mandant:string:index \
  client_system:string:index \
  --no-stylesheets --no-javascripts --no-helper
----

.Unique Index for TerminalWorkplaces
[source,ruby]
----
t.index [:card_terminal_id, :mandant,\
         :client_system, :workplace_id], unique: true
t.index [:workplace_id, :card_terminal_id]
t.index [:card_terminal_id, :workplace_id]
----