require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/connectors", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Connector. As you add validations to Connector, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Connector.create! valid_attributes
      get connectors_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      connector = Connector.create! valid_attributes
      get connector_url(connector)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_connector_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      connector = Connector.create! valid_attributes
      get edit_connector_url(connector)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Connector" do
        expect {
          post connectors_url, params: { connector: valid_attributes }
        }.to change(Connector, :count).by(1)
      end

      it "redirects to the created connector" do
        post connectors_url, params: { connector: valid_attributes }
        expect(response).to redirect_to(connector_url(Connector.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Connector" do
        expect {
          post connectors_url, params: { connector: invalid_attributes }
        }.to change(Connector, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post connectors_url, params: { connector: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested connector" do
        connector = Connector.create! valid_attributes
        patch connector_url(connector), params: { connector: new_attributes }
        connector.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the connector" do
        connector = Connector.create! valid_attributes
        patch connector_url(connector), params: { connector: new_attributes }
        connector.reload
        expect(response).to redirect_to(connector_url(connector))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        connector = Connector.create! valid_attributes
        patch connector_url(connector), params: { connector: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested connector" do
      connector = Connector.create! valid_attributes
      expect {
        delete connector_url(connector)
      }.to change(Connector, :count).by(-1)
    end

    it "redirects to the connectors list" do
      connector = Connector.create! valid_attributes
      delete connector_url(connector)
      expect(response).to redirect_to(connectors_url)
    end
  end
end
