require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/kt_proxies", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # KTProxy. As you add validations to KTProxy, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      KTProxy.create! valid_attributes
      get kt_proxies_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      kt_proxy = KTProxy.create! valid_attributes
      get kt_proxy_url(kt_proxy)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_kt_proxy_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      kt_proxy = KTProxy.create! valid_attributes
      get edit_kt_proxy_url(kt_proxy)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new KTProxy" do
        expect {
          post kt_proxies_url, params: { kt_proxy: valid_attributes }
        }.to change(KTProxy, :count).by(1)
      end

      it "redirects to the created kt_proxy" do
        post kt_proxies_url, params: { kt_proxy: valid_attributes }
        expect(response).to redirect_to(kt_proxy_url(KTProxy.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new KTProxy" do
        expect {
          post kt_proxies_url, params: { kt_proxy: invalid_attributes }
        }.to change(KTProxy, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post kt_proxies_url, params: { kt_proxy: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested kt_proxy" do
        kt_proxy = KTProxy.create! valid_attributes
        patch kt_proxy_url(kt_proxy), params: { kt_proxy: new_attributes }
        kt_proxy.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the kt_proxy" do
        kt_proxy = KTProxy.create! valid_attributes
        patch kt_proxy_url(kt_proxy), params: { kt_proxy: new_attributes }
        kt_proxy.reload
        expect(response).to redirect_to(kt_proxy_url(kt_proxy))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        kt_proxy = KTProxy.create! valid_attributes
        patch kt_proxy_url(kt_proxy), params: { kt_proxy: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested kt_proxy" do
      kt_proxy = KTProxy.create! valid_attributes
      expect {
        delete kt_proxy_url(kt_proxy)
      }.to change(KTProxy, :count).by(-1)
    end

    it "redirects to the kt_proxies list" do
      kt_proxy = KTProxy.create! valid_attributes
      delete kt_proxy_url(kt_proxy)
      expect(response).to redirect_to(kt_proxies_url)
    end
  end
end
