require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/operational_states", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # OperationalState. As you add validations to OperationalState, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      OperationalState.create! valid_attributes
      get operational_states_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      operational_state = OperationalState.create! valid_attributes
      get operational_state_url(operational_state)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_operational_state_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      operational_state = OperationalState.create! valid_attributes
      get edit_operational_state_url(operational_state)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new OperationalState" do
        expect {
          post operational_states_url, params: { operational_state: valid_attributes }
        }.to change(OperationalState, :count).by(1)
      end

      it "redirects to the created operational_state" do
        post operational_states_url, params: { operational_state: valid_attributes }
        expect(response).to redirect_to(operational_state_url(OperationalState.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new OperationalState" do
        expect {
          post operational_states_url, params: { operational_state: invalid_attributes }
        }.to change(OperationalState, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post operational_states_url, params: { operational_state: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested operational_state" do
        operational_state = OperationalState.create! valid_attributes
        patch operational_state_url(operational_state), params: { operational_state: new_attributes }
        operational_state.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the operational_state" do
        operational_state = OperationalState.create! valid_attributes
        patch operational_state_url(operational_state), params: { operational_state: new_attributes }
        operational_state.reload
        expect(response).to redirect_to(operational_state_url(operational_state))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        operational_state = OperationalState.create! valid_attributes
        patch operational_state_url(operational_state), params: { operational_state: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested operational_state" do
      operational_state = OperationalState.create! valid_attributes
      expect {
        delete operational_state_url(operational_state)
      }.to change(OperationalState, :count).by(-1)
    end

    it "redirects to the operational_states list" do
      operational_state = OperationalState.create! valid_attributes
      delete operational_state_url(operational_state)
      expect(response).to redirect_to(operational_states_url)
    end
  end
end
