= Certificate Authority für Clientsysteme
:author: Wolfgang Barth
:navtitle: CA für Clientsysteme
:revdate: 2024-10-03

* Referenz: https://openssl-ca.readthedocs.io/en/latest

== CA aufsetzen

----
mkdir /etc/ssl/telematik
cd /etc/ssl/telematik
mkdir certs crl newcerts private reqs
chmod 700 private
touch index.txt
echo 1000 > serial
----

----
cp /etc/ssl/openssl.cnf /etc/ssl/telematik/.
----

#FIXME# #TBD#

NOTE: Die bisherige Dokumentation basiert auf RSA-2048 und 
muss wegen Umstellung auf ECC überarbeitet werden

== Memo

.Beispiel aus gemSpec_Krypt_V2.36.0 [A_23511] - Konnektor, IOP, Kodierung ECC-Schlüssel, PrimärsystemVerbindungssicherung
----
openssl ecparam -name brainpoolP256r1 \
  -genkey -param_enc named_curve \
  -out example-named-curve-private-key.pem
----

////
openssl genpkey -algorithm ec \
  -out private/cakey.pem -aes-256-cbc \
  -pkeyopt ec_paramgen_curve:brainpoolP256r1 \
  -pkeyopt ec_param_enc:named_curve

----
openssl genpkey -genparam -algorithm ec -out ec-params.pem \
  -pkeyopt ec_paramgen_curve:brainpoolP256r1 \
  -pkeyopt ec_param_enc:named_curve

openssl genpkey -paramfile ec-params.pem \
  -out private/cakey.pem -aes-256-cbc
----

$ openssl genpkey -genparam -algorithm ec -pkeyopt ec_paramgen_curve:secp384r1 -out server.key.params.pem
$ openssl genpkey -paramfile server.key.params.pem -out private/server.key.pem
$ openssl req -new -config 'server.cert.conf' -key 'private/server.key.pem' -out 'server.csr.pem'
////

.CA-Key
----
openssl genpkey -genparam -algorithm ec -out ec-params.pem \
  -pkeyopt ec_paramgen_curve:brainpoolP256r1 \
  -pkeyopt ec_param_enc:named_curve

openssl genpkey -paramfile ec-params.pem \
  -out private/cakey.pem -aes-256-cbc

chmod 400 private/cakey.pem
----

////
bearbeiten


.CA-Key
----
openssl genrsa -aes256 -out private/cakey.pem 3072
chmod 400 private/cakey.pem
----

.CA-Zertifikat
----
openssl req -config openssl.cnf -key private/cakey.pem \
    -new -x509 -days 7300 -sha256 -extensions v3_ca \
    -out certs/cacert.pem
chmod 4444 certs/cacert.pem    
openssl x509 -noout -text -in certs/cacert.pem
----

== Zertifikat für Client-System

.PKey
----
openssl genrsa -aes256 -out private/intern.key.pem 3072
chmod 400 private/intern.key.pem
----

.Request
----
openssl req -config openssl.cnf \
    -key private/intern.key.pem \
    -new -sha256 -out reqs/intern.req.pem 
----

.Zertifikat für Client-System
----
openssl ca -config openssl.cnf -days 1825 \
  -in reqs/intern.req.pem \
  -out certs/intern.cert.pem
chmod 444 certs/intern.cert.pem
openssl x509 -noout -text -in certs/intern.cert.pem
----

.Export als PKCS12
----
openssl pkcs12 -export -out certs/intern.p12 \
    -inkey private/intern.key.pem \
    -in certs/intern.cert.pem \
    -certfile certs/cacert.pem
----

////