@startuml

state OK #lightgreen
OK: CardTerminal online

state WARNING #Yellow
WARNING: CardTerminal nicht verbunden, oder
WARNING: verbunden, aber kein Ping

state CRITICAL #orangered
CRITICAL: CardTerminal nicht erreichbar

note right of CRITICAL
Erreichbar ==
Ping oder "connected"
endnote

state UNKNOWN #LightSkyBlue
UNKNOWN: keine gültige IP
UNKNOWN: IP Mismatch

state NOTHING #LightGrey
NOTHING: Kein Connector eingetragen

NOTHING --> UNKNOWN
UNKNOWN --> CRITICAL
CRITICAL --> WARNING
WARNING --> OK
@enduml