@startuml

state OK #lightgreen
OK: Connector erreichbar
OK: fetch SDS ok
OK: VPNTI-Status "Online"

'state WARNING #Yellow
'WARNING: Connector erreichbar
'WARNING: fetch SDS ok
'WARNING: VPNTI-Status "Offline"

state CRITICAL #orangered
CRITICAL: Connector nicht erreichbar
CRITICAL: VPNTI-Status "Offline"
CRITICAL: Zertifikat abgelaufen

'state WARNING #Yellow
'WARNING: Zertifikat des Konnektors läuft bald ab
'WARNING: Reboot angestoßen

state UNKNOWN #LightSkyBlue
UNKNOWN: Connector erreichbar
UNKNOWN: fetch SDS failed or 
UNKNOWN: GetResourceInformation failed

state NOTHING #LightGrey
NOTHING: Nicht konfiguriert;
NOTHING: Manuelles Update aktiviert;

NOTHING --> UNKNOWN
UNKNOWN --> CRITICAL
'CRITICAL --> WARNING
'WARNING --> OK
CRITICAL --> OK
@enduml