@startuml

participant "KTProxy" as ktproxy #gold
participant "RISE::TIClient::CardTerminals" as ticlient #gold


ktproxy -> ticlient : get_proxy\n(ktproxy)
ticlient ->] : GET /v1/manager/card-terminals/proxies/{id}
]--> ticlient : Response (cardterminal_proxies.json)
ticlient -> ktproxy : ktproxy.json

ktproxy -> ticlient : create_proxy\n(ktproxy)
ticlient ->] : POST /v1/manager/card-terminals/proxies
]--> ticlient : Response (proxy.json)
ticlient --> ktproxy : ktproxy.json

ktproxy -> ticlient : update_proxy\n(ktproxy)
ticlient ->] : POST /v1/manager/card-terminals/proxies/{id}
]--> ticlient : Response (status)
ticlient --> ktproxy : true/false

ktproxy -> ticlient : destroy_proxy\n(ktproxy)
ticlient ->] : POST /v1/manager/card-terminals/proxies/{id}
]--> ticlient : Response (status)
ticlient --> ktproxy : true/false

@enduml