@startuml
top to bottom direction

!theme cocard from .

class Connector  {
  name: string
  description: rich_text
  ip: inet
  admin_url: string
  sds_url: string
  manual_update: boolean
  id_contract: string
  serial: string
  use_tls: boolean
  authentication: integer
  --
  sds_xml: text
  sds_updated_at: timestamp
  connector_services: jsonb
  last_check: timestamp
  last_check_ok: timestamp
  condition: integer
  condition_message: string
  soap_request_success: boolean
  vpnti_online: boolean
  firmware_version: string
}

class CardTerminal {
  displayname: string
  description: rich_text
  room: string
  contact: string
  plugged_in: string
  delivery_date: date
  supplier: string
  serial: string
  id_product: string
  location_id
  --
  properties: jsonb
  name: string
  ct_id: string
  mac: macaddr
  ip: inet
  slots: integer
  connected: boolean
  condition_message: string
  condition: integer
  firmware_version: string
  connector_id
}

class Location {
  lid: string
  description: string
}

class Context {
  mandant: string
  client_system: string
  workplace: string
  description: string
}

class ConnectorContext {
  connector_id
  context_id
  position: integer
}

class Card {
  name: string
  description: rich_text
  operational_state_id
  location_id
  lanr: string
  fachrichtung: string
  bsnr: string
  telematikid: string
  private_information: rich_text
  context_id
  --
  properties: jsonb
  card_handle: string
  card_type: string
  iccsn: string
  slotid: integer
  insert_time: timestamp
  card_holder_name: string
  expiration_date: date
  condition: integer
  condition_message: string
  pin_status: string
  card_terminal_id
  --
  certificate:text
  cert_subject_cn: string
  cert_subject_title: string
  cert_subject_sn: string
  cert_subject_givenname: string
  cert_subject_street: string
  cert_subject_postalcode: string
  cert_subject_l: string
  cert_subject_o: string
}

class Workplace {
  description: string
  --
  name: string
}
Class TerminalWorkplaces {
  card_terminal_id
  workplace_id
  mandant: string
  client_system: string
  updated_at
}
Class OperationalState {
  name: string
  description: string
  operational: boolean
}

Class Log {
  loggable: polymorphic
  action: string
  last_seen: timestamp
  since: timestamp
  level: string
  message: text
  is_valid: boolean
  condition: integer
}

Class Network {
  netzwerk: cidr
  description: rich_text
  location_id
}

Class ClientCertificate {
  name: string
  client_system: string
  description: rich_text
  cert: text
  pkey: text
  passphrase: string
  cn()
}

Network "*" - "1" Location
Location "*" -- "*" Connector
Context "*" -- "*" Connector
Connector "0..1" - "*" CardTerminal
Location "0..1" -- "*" CardTerminal
(Connector, Context) . ConnectorContext
CardTerminal "0..1" - "*" Card
CardTerminal "*" -- "*" Workplace
TerminalWorkplaces . (CardTerminal, Workplace) 
Location "0..1" -- "*" Card
OperationalState "1" -- "*" Card
Context "1" -- "*" Card

Connector "1" -- "*" Log
CardTerminal "1" -- "*" Log
Card "1" -- "*" Log

Connector "*" -- "*" ClientCertificate
@enduml
