@startuml
top to bottom direction

!theme cocard from .

class Connector  {
  name: string
  description: rich_text
  ip: inet
  sds_url: string
  manual_update: boolean
  --
  sds_xml: text
  sds_updated_at: timestamp
  connector_services: jsonb
  last_check: timestamp
  last_check_ok: timestamp
  condition: integer
  soap_request_success: boolean
  vpnti_online: boolean
}

class CardTerminal {
  description: rich_text
  --
  connector_id
  name: string
  properties: jsonb
  last_check: timestamp
  last_check_ok: timestamp
  condition: integer
  ctid: string
  mac: macaddr
  ip: inet
  connected: boolean
  last_seen: timestamp
}

class Location {
  lid: string
  description: string
}

class Context {
  mandant: string
  client_system: string
  workplace: string
  description: string
}

class ConnectorContext {
  connector_id
  context_id
  position: integer
}


Location "*" -- "*" Connector
Context "*" -- "*" Connector
Connector "1" -- "*" CardTerminal

(Connector, Context) .. ConnectorContext

@enduml
