= Changelog

== 0.9.4-dev - unreleased

* Kontext-Check zum Konnektor: Abfrage eines beliebigen Kontextes beim Konnektor über GetResourceInformation.
* RISE TIClient: Abfrage der Kartenterminals und deren Zustände am Konnektor über die Proxy-Funktion des TI-Clients - erfordert Aktivierung (z.Z. nur manuell z.B. via Bruno möglich)
* RISE TIClient: Terminal dem Konnektor zuweisen (BEKANNT->ZUGEWIESEN)
* RISE TIClient: Terminal pairen. Dabei startet Cocard das Pairing auf einem Orga6141 und führt das Pairing am Konnektor durch
* RISE TIClient: Anzeige von Remote PIN Plus Konfigurationen
* Orga6141: Ausgabe statistischer Informationen (Steckzyklen, Uptime, Laufzeit gesamt)
* Konnektor-Kontexte: Sortierung per Drag and Drop möglich

== 0.9.3 - 2025-11-08

* (experimentell) Abgleich KT-Proxys über RISE TI-Client-API
* (experimentell) Create/update/delete eines Proxys auf dem RISE TI-Client bei Anlage eines KTProxy in Cocard.
* Anzeige Konnektor: zugeordnete SMC-Bs aufgenommen und Layout überarbeitet
* Tabelle Zuordung Terminals - Arbeitsplätze erweitert
* Status Kartenterminal ist jetzt UNNKOWN, wenn es online ist, aber der Konnektor nicht OK.
* kleinere Bugfixe

== 0.9.2 - 2025-10-19

* Bugfixe und Layout-Anpassungen
* Arbeitsplätze: _zuletzt gesehen_ ergänzt
* Tabelle Terminals - Arbeitsplätze jetzt mit _zuletzt aktualisiert_
 
== 0.9.1 - 2025-10-11

* Bugfix Health-Check bei Orga6141 mit Firmware 3.9.0
* Kartenterminals: Firmware-Version und Identifikation editierbar, falls Kartenterminal neu in Betrieb genommen wird und noch keine Produkt-Identifikation über den Konnektor vorliegt. Cocard benötigt die Identifikation des Terminals für das Anstoßen des Pairings.
* Konnektor: ein Zertifikatsablauf in weniger als 90 Tagen geht nicht mehr in den Gesamtzustand ein, sondern wird separat dargestellt. Nur ein abgelaufenes Zertifikat wird beim Gesamtzustand berücksichtigt.
* Kartenterminal: Check über IP-Adresse möglich, wenn RMI für das Terminal unterstützt wird. Ist noch kein Kartenterminal mit der MAC-Adresse vorhanden, wird das Terminal neu angelegt.
* Zuordnung Terminals - Arbeitsplätze jetzt ein einer einzigen Tabelle. Bisher wurden Arbeitsplätze nur einzeln beim jeweiligen Kartenterminal angezeigt.
* PIN-Verifizierung: Hinweis im Kontext, falls die Authentifikation nicht vollständig gepflegt ist (z.B. wenn beim Konnektor kein passendes Zertifikat zum Clientsystem hinterlegt ist)
* Bugfix: Tags wurden durch Hintergrundjobs gelöscht und gingen verloren; Fehler ist behoben


== 0.9.0 - 2025-09-27

* Suchfunktion für die Online-Dokumentation
* [experimental] Unterstützung für KT-Proxys (RISE TI-Gateway) 
* Refactoring der RMI-Schnittstellen für Kartenterminals und Konnektoren
* Kartenterminals: Reboot für Orga 6141 wieder hergestellt.
* Kartenterminals: Remote Pairing für Orga 6141 ab Version 3.9.1
* Kartenterminals: Report Terminals mit doppelter IP
* Kartenterminals: doppelte IPs werden entfernt, wenn ein Kartenterminal mit der gleichen IP aktuell als aktiv und OK über den Konnektor beim Scan gefunden wird.
* Kartenterminals: Health-Check erweitert - prüft per RMI wenn möglich auch MAC-Adresse und Terminalname gegen die Cocard-Konfiguration.

== 0.8.5 - 2025-08-31

* Kartenterminal: trennt man den Konnektor, wird die CT_ID und die vom Konnektor gefundene IP gelöscht.
* Client-Zertifikate: alternative Auswahl des verwendeten Client-Zertifikates via Tag. Bisher musste `CN=<client_system>` sein, damit Cocard das Client-Zertifikat passend zum Kontext ausgewählt hat.
* Automatischer Reboot von Konnektoren erzeugt per Default keine Notiz mehr.

== 0.8.4 - 2025-08-17

* Karte kopieren: existierende Karte kann als Vorlage bei Nachbestellungen verwendet werden.
* Automatischer Reboot von Konnektoren: Fallback auf Default-Croneinstellungen für den Job wenn die Syntax der Variable CRON_REBOOT_CONNECTORS ungültig ist.

== 0.8.3 - 2025-07-13

* Konnektor: Buttons für Reboot und Connectivity-Check jetzt auch auf der Übersichtsseite der Konnektoren
* `fping` statt `ping` für Verbindungstests (robuster und schneller bei Erreichbarkeit)
* Kartenterminal: Reset-Button zum einfacheren Löschen der Konnektor-Verbindung (wenn Kartenterminal != OK)
* Automatischer Reboot von unterstützten Konnektoren (KoCoBox)

== 0.8.2 - 2025-06-28

* ObjectSystemVersion einer Karte. SMC-B, HBA und gSMC-KT mit einer ObjectSystemVersion < 4.4.0 sind RSA only, HBAs dürfen für die QES ab 01.01.2026 nur noch ECC verwenden. Bei nonQES-Verfahren gilt eine Duldung bis Ende 2026.
* Dokumentation für Karte und Tags ergänzt

== 0.8.1 - 2025-06-07

* Kartenterminal: Firmwareversion ins Formular mit aufgenommen für manuellen 
  Eintrag bei mobilen Kartenterminals
* Tags für die objekt-übergreifende Kennzeichnung
* Fix: Standort bei Karten wird nicht mehr überschrieben, wenn dem Kartenterminal kein Standort zugewiesen ist.

== 0.8.0 - 2025-05-13

* Authentifikation gegen LDAP parallel zur lokalen Datenbank
* Benutzeranlage mit Vorlage aus einem LDAP-Verzeichnisdienst
* Upgrade auf Ruby 3.3

== 0.7.8 - 2025-05-08

* Fix: Der Wechsel einer Karte von einem Slot zu einem anderen (oder auch anderem Kartenterminal) wird jetzt korrekt dargestellt.
* `last_check` für Karten und Terminals (letztes Auffinden über den Konnektor)
* Hintergrundjob für das Aufräumen bei abgelaufenen Acknowledges insbesondere
für Objekte, die aus anderen Gründen nicht mehr aktualisiert werden.
* Reset-Button bei Karten zum Löschen der Zuordnung zum Kartenterminals insbesondere für außer Betrieb genommene Karten.
* Soft delete für Karten: _Löschen_ versteckt die Karte, löscht sie aber nicht vollends aus der Datenbank. Über den Menüeintrag _Gelöschte Karten_ können diese Karten weiter eingesehen werden. Karten, die vor diesem Release gelöscht wurden, sind dauerhaft gelöscht.

== 0.7.7 - 2025-05-04

* Fix: Karten mit abgelaufenen Acknowledges werden wieder korrekt im Dashboard angezeigt
* Suche nach abgelaufenen und nicht mehr benutzten Karten
* IP Mismatch bei Kartenterminals: Anzeige der IPs jetzt auch in der Fehlermeldung

== 0.7.6 - 2025-04-13

* Ruhebildschirm setzen: Feedback bei Fehlern verbessert
* Reboot KoCoBox: Feedback bei SSL-Fehlern, die einen Remote-Reboot verhindern
* Prüfung Kartenterminal, ob Remote-Management-Port für RMI verfügbar ist.
* Update auf Ruby 3.2.7
* Verbindungstest für Konnektor und Kartenterminal separat via Button möglich

== 0.7.5 - 2025-04-05

* internes Refactoring bei Funktionen für unterstützte Kartenterminals
* Fix: Aktualisierung der Notizen im Dashboard bei Änderungen
* Fix: Update der Anzeige bei Aktualisierung des TI-Lagebildes durch den Hintergrundjob
* Link und Edit-Button bei Notizen im Dashboard (Edit nur bei Owner)
* kleinere Bugfixes

== 0.7.4 - 2025-03-14

* HOTFIX: Problem beim Reinitialisieren von Tabellen behoben.

== 0.7.3 - 2025-03-14

* Übersicht Kartenterminals: Performance bei großer Anzahl von Terminals 
  verbessert (umgestellt auf server side processing)

== 0.7.2 - 2025-03-08

* Update des Ruhebildschirms (Anzeige im Display) für ORGA 6141 online Terminals
* Rebootmöglichkeit von ORGA 6141 online Terminals.
* Hinweis bei fehlendem Kontext für Konnektor und Karte.

== 0.7.0 - 2025-02-22

=== BREAKING CHANGES

* Änderung des Modells für die Zuordnung von Karten zu Kartenterminals. Jeder Slot kann jetzt nur noch genau eine Karte zugeordnet haben. Beim Wechsel einer Karte wie SMC-KT wird die neue (von Cocard gefundene) Karte dem Slot zugeordnet, die bisherige Karte entfernt und erhält den Status NOTHING. Damit ist sichergestellt, dass die SMC-KT, die beim Kartenterminal angezeigt wird, immer die aktuelle Karte ist und jeder Slot nur eine zugeordnete Karte haben kann (bisher: ein Kartenterminal konnte mehrere Karten pro Slot zugeordnet haben).

== 0.6.5 - 2025-02-08

* Fix: update von last_ok korrigiert, war bisher vor allem beim Konnektor nicht immer korrekt
* Update diverser Abhängigkeiten


== 0.6.4 - 2025-02-01

* SMC-B und SMC-KT übernehmen den Ort vom Kartenterminal beim Speichern
* Liste aller Kartenterminals mit SMC-B
* Gesamtübersicht über alle Notizen
* Anzeige der aktuellsten Notizen im Dashboard
* Anzeige SMC-KT ICCSN und Gültigkeit beim Kartenterminal und in der Übersicht der Kartenterminals
* Ändert sich die IP des Kartenterminals, muss diese manuell übernommen werden. Die einmal eingestellte IP bleibt bis zur manuellen Übernahme erhalten, auch dann, wenn das Kartenterminal wegen eines Problems seine IP verliert.
* Dokumentation für Kartenterminals ergänzt

== 0.6.3 - 2025-01-17
* Workflow für die PIN-Verifizierung aller Karten eines Terminals verbessert.
* Neu: Hintergrundjob für die automatische PIN-Verifizierung (nur unterstützte Terminals). SMC-B Auto-PIN-Mode muss hierfür am Kartenterminal gleich `Automatisch` sein. xref:admin/card-terminal-edit.adoc[Mehr zur automatischen PIN-Verifizierung]
* Neu: Einzelne Einträge des TI-Lagebildes können gemutet werden, um nicht relevante Einträge aus dem Gesamtstatus herauszunehmen
* Fix: TI-Lagebild: die Anzeige der fehlerhaften Dienste korrigiert.

== 0.6.2 - 2025-01-11

* Wird der Konnektor über Cocard gebootet, ist der Status WARNING (gelb) und wird mit dem Reboot-Datum angegeben, bis der Konnektor wieder ok ist.
* Fehlermeldungen enthalten jetzt den Code und Zusatzangaben, falls der Konnektor solche liefert (gemSpec_OM 3.2.1 Feld Detail)
* Kartenterminal mit IP = 0.0.0.0 hat jetzt den Status UNKNOWN

== 0.6.1 - 2024-12-24

* Neu: Reboot von KoCoBox-Konnektoren
* Geschütze Information wird erst nach Userinteraktion angezeigt (bei Karte und Konnektor).
* Dokumentation für Konnektoren ergänzt

== 0.6.0 - 2024-12-14

* Update auf Rails 7.2
* Konfigurationscheck prüft beim Konnektor, ob der Port für SDS und der SOAP-Port erreichbar sind.

== 0.5.0 - 2024-12-08

* Neu: xref:admin/connector-edit.adoc#_authentifikation_per_userpasswort[Client-Authentifikation am Konnektor mit User/Passwort] (alternativ zum Client-Zertifikat)
* Fix: Löschen von Objekten mit verbesserter Fehlermeldung
* Einzelne Logs auf ungültig setzen (bisher nur alle veralteten Logs auf einmal)

== 0.4.7 - 2024-11-30

* Fix: Clientzertifikat P12-Import jetzt auch mit Legacy-Formaten möglich, 
  sofern openssl -legacy das Format unterstützt (OpenSSL-Version 3.x). Kocoboxen erzeugen noch P12 in einem Legacy-Format.
* Update TI-Lagebild-Button
* Logeinträge: neue Funktion veraltete Logeinträge auf ungültig setzen

== 0.4.6 - 2024-11-08

* Fix: Einzelanzeige Kontext zeigt jetzt die Tabellen Konnektoren/Karten korrekt.
* Update PIN-Status nach PIN-Verify, um die Änderung unmittelbar anzuzeigen.
* Anzeige Arbeitsplätze überarbeitet; Löschfunktion für veraltete Arbeitsplätze
* Dokumentation für Arbeitsplätze ergänzt
* Verbesserung TI-Lagebild: Unterscheidung zwischen Teil- (WARNING) und Totalausfall eines Dienstes (CRITICAL)


== 0.4.5 - 2024-11-02

* Neu: xref:user/ti-lagebild.adoc[TI-Lagebild]: Anzeige von Störungen der 
  Telematik-Infrastruktur
* Dokumentation zur xref:user/verify-pin.adoc[PIN-Verifizierung] ergänzt

== 0.4.4 - 2024-10-06

* Neu: Import von Client-Zertifikaten als P12-Datei

== 0.4.3 - 2024-10-03

* Update der Dokumentation
* Fix: keine SOAP-Abfrage, wenn der Konnektor noch keine SDS-Informationen hat.

== 0.4.2 - 2024-10-02

* Abfrage der SMC-K Daten vom Konnektor (ICCSN, Gültigkeit bis) (1x pro Tag)
* Aktualisierung des Card-Handles bei der Sammelaktion VerifyPin pro Kartenterminal.

== 0.4.1 - 2024-09-27

* Verbesserte Info-Ausgaben bei Nutzung der SMC-B Remote PIN
* Separate Übersicht veralteter Logeinträge mit der Möglichkeit alle zu löschen

== 0.4.0 - 2024-09-21

* Acknowledges und Notizen für Konnektoren, Karten und Kartenterminals
* Bugfix für Seitenaktualisierung bei Karte bei Aktion VerifyPin/GetPinStatus

== 0.3.8 - 2024-09-14

* xref:admin/smcb-remote-pin.adoc[Remote-SMC-B PIN Support für ORGA 6141 online]

== 0.3.7 - 2024-09-14

* Fix: Fehlermeldung bei erfolreicher Pin-Verifikation korrigiert
* Acknowledge-Button jetzt auch im Log-Bereich von Konnektor/Karte/Terminal (bisher: nur im Dashboard)

== 0.3.6 - 2024-09-10

* Neu: xref:user/acknowledges.adoc[Acknowledges und Notizen für Log-Einträge]

== 0.35 - 2024-08-31

* xref:admin/authorities.adoc[Erweiterung der Berechtigungsverwaltung]

== 0.34 - 2024-08-30

* Fix: Überprüfung auf doppelte MACs bei Kartenterminal
* Fix: Konnektoren ohne Kartenterminal liefern unvollständige SOAP-Nachricht
* Change: VerifyPin mit 2 Sekunden Delay zwischen zwei PIN-Eingaben
* Change: Klick auf Konnektor in Eventlogs im Dashboard ohne Anchor
* Change: Überarbeitung der Ausgaben bei VerifyPin, PinStatus und GetCard (einheitlich als Toast- statt Flash-Nachricht)
