= Changelog

== 0.7.1 - unreleased

== 0.7.0 - 2025-02-22

=== BREAKING CHANGES

* Änderung des Modells für die Zuordnung von Karten zu Kartenterminals. Jeder Slot kann jetzt nur noch genau eine Karte zugeordnet haben. Beim Wechsel einer Karte wie SMC-KT wird die neue (von Cocard gefundene) Karte dem Slot zugeordnet, die bisherige Karte entfernt und erhält den Status NOTHING. Damit ist sichergestellt, dass die SMC-KT, die beim Kartenterminal angezeigt wird, immer die aktuelle Karte ist und jeder Slot nur eine zugeordnete Karte haben kann (bisher: ein Kartenterminal konnte mehrere Karten pro Slot zugeordnet haben).

== 0.6.5 - 2025-02-08

* Fix: update von last_ok korrigiert, war bisher vor allem beim Konnektor nicht immer korrekt
* Update diverser Abhängigkeiten


== 0.6.4 - 2025-02-01

* SMC-B und SMC-KT übernehmen den Ort vom Kartenterminal beim Speichern
* Liste aller Kartenterminals mit SMC-B
* Gesamtübersicht über alle Notizen
* Anzeige der aktuellsten Notizen im Dashboard
* Anzeige SMC-KT ICCSN und Gültigkeit beim Kartenterminal und in der Übersicht der Kartenterminals
* Ändert sich die IP des Kartenterminals, muss diese manuell übernommen werden. Die einmal eingestellte IP bleibt bis zur manuellen Übernahme erhalten, auch dann, wenn das Kartenterminal wegen eines Problems seine IP verliert.
* Dokumentation für Kartenterminals ergänzt

== 0.6.3 - 2025-01-17
* Workflow für die PIN-Verifizierung aller Karten eines Terminals verbessert.
* Neu: Hintergrundjob für die automatische PIN-Verifizierung (nur unterstützte Terminals). SMC-B Auto-PIN-Mode muss hierfür am Kartenterminal gleich `Automatisch` sein. xref:admin/card-terminal-edit.adoc[Mehr zur automatischen PIN-Verifizierung]
* Neu: Einzelne Einträge des TI-Lagebildes können gemutet werden, um nicht relevante Einträge aus dem Gesamtstatus herauszunehmen
* Fix: TI-Lagebild: die Anzeige der fehlerhaften Dienste korrigiert.

== 0.6.2 - 2025-01-11

* Wird der Konnektor über Cocard gebootet, ist der Status WARNING (gelb) und wird mit dem Reboot-Datum angegeben, bis der Konnektor wieder ok ist.
* Fehlermeldungen enthalten jetzt den Code und Zusatzangaben, falls der Konnektor solche liefert (gemSpec_OM 3.2.1 Feld Detail)
* Kartenterminal mit IP = 0.0.0.0 hat jetzt den Status UNKNOWN

== 0.6.1 - 2024-12-24

* Neu: Reboot von KoCoBox-Konnektoren
* Geschütze Information wird erst nach Userinteraktion angezeigt (bei Karte und Konnektor).
* Dokumentation für Konnektoren ergänzt

== 0.6.0 - 2024-12-14

* Update auf Rails 7.2
* Konfigurationscheck prüft beim Konnektor, ob der Port für SDS und der SOAP-Port erreichbar sind.

== 0.5.0 - 2024-12-08

* Neu: xref:admin/connector-edit.adoc#_authentifikation_per_userpasswort[Client-Authentifikation am Konnektor mit User/Passwort] (alternativ zum Client-Zertifikat)
* Fix: Löschen von Objekten mit verbesserter Fehlermeldung
* Einzelne Logs auf ungültig setzen (bisher nur alle veralteten Logs auf einmal)

== 0.4.7 - 2024-11-30

* Fix: Clientzertifikat P12-Import jetzt auch mit Legacy-Formaten möglich, 
  sofern openssl -legacy das Format unterstützt (OpenSSL-Version 3.x). Kocoboxen erzeugen noch P12 in einem Legacy-Format.
* Update TI-Lagebild-Button
* Logeinträge: neue Funktion veraltete Logeinträge auf ungültig setzen

== 0.4.6 - 2024-11-08

* Fix: Einzelanzeige Kontext zeigt jetzt die Tabellen Konnektoren/Karten korrekt.
* Update PIN-Status nach PIN-Verify, um die Änderung unmittelbar anzuzeigen.
* Anzeige Arbeitsplätze überarbeitet; Löschfunktion für veraltete Arbeitsplätze
* Dokumentation für Arbeitsplätze ergänzt
* Verbesserung TI-Lagebild: Unterscheidung zwischen Teil- (WARNING) und Totalausfall eines Dienstes (CRITICAL)


== 0.4.5 - 2024-11-02

* Neu: xref:user/ti-lagebild.adoc[TI-Lagebild]: Anzeige von Störungen der 
  Telematik-Infrastruktur
* Dokumentation zur xref:user/verify-pin.adoc[PIN-Verifizierung] ergänzt

== 0.4.4 - 2024-10-06

* Neu: Import von Client-Zertifikaten als P12-Datei

== 0.4.3 - 2024-10-03

* Update der Dokumentation
* Fix: keine SOAP-Abfrage, wenn der Konnektor noch keine SDS-Informationen hat.

== 0.4.2 - 2024-10-02

* Abfrage der SMC-K Daten vom Konnektor (ICCSN, Gültigkeit bis) (1x pro Tag)
* Aktualisierung des Card-Handles bei der Sammelaktion VerifyPin pro Kartenterminal.

== 0.4.1 - 2024-09-27

* Verbesserte Info-Ausgaben bei Nutzung der SMC-B Remote PIN
* Separate Übersicht veralteter Logeinträge mit der Möglichkeit alle zu löschen

== 0.4.0 - 2024-09-21

* Acknowledges und Notizen für Konnektoren, Karten und Kartenterminals
* Bugfix für Seitenaktualisierung bei Karte bei Aktion VerifyPin/GetPinStatus

== 0.3.8 - 2024-09-14

* xref:admin/smcb-remote-pin.adoc[Remote-SMC-B PIN Support für Orga6141]

== 0.3.7 - 2024-09-14

* Fix: Fehlermeldung bei erfolreicher Pin-Verifikation korrigiert
* Acknowledge-Button jetzt auch im Log-Bereich von Konnektor/Karte/Terminal (bisher: nur im Dashboard)

== 0.3.6 - 2024-09-10

* Neu: xref:user/acknowledges.adoc[Acknowledges und Notizen für Log-Einträge]

== 0.35 - 2024-08-31

* xref:admin/authorities.adoc[Erweiterung der Berechtigungsverwaltung]

== 0.34 - 2024-08-30

* Fix: Überprüfung auf doppelte MACs bei Kartenterminal
* Fix: Konnektoren ohne Kartenterminal liefern unvollständige SOAP-Nachricht
* Change: VerifyPin mit 2 Sekunden Delay zwischen zwei PIN-Eingaben
* Change: Klick auf Konnektor in Eventlogs im Dashboard ohne Anchor
* Change: Überarbeitung der Ausgaben bei VerifyPin, PinStatus und GetCard (einheitlich als Toast- statt Flash-Nachricht)
