- hosts: 127.0.0.1
  connection: local
  vars_files:
    - vars/secure.yml
  vars:
    postgres_users_no_log: false
    postgresql_databases:
      - name: cocard_development
        owner: cocard
        lc_collate: de_DE.UTF-8
        lc_ctype: de_DE.UTF-8

      - name: cocard_test
        owner: cocard
        lc_collate: de_DE.UTF-8
        lc_ctype: de_DE.UTF-8

    postgresql_users:
      - name: Cocard
        password: "{{ postgresql_user_password }}"
        encrypted: yes

  roles:
    - role: geerlingguy.postgresql
      become: yes
