- hosts: 127.0.0.1
  connection: local
  become: yes
  vars_files:
    - vars/secure.yml
  vars:
    postgres_users_no_log: false
    # don't touch pg_hba.conf with empty list
    postgresql_hba_entries: {}
    postgresql_users:
      - name: cocard
        password: "{{ postgresql_user_password }}"
        encrypted: yes
    postgresql_databases:
      - name: cocard_development
        owner: cocard
        lc_collate: de_DE.UTF-8
        lc_ctype: de_DE.UTF-8

      - name: cocard_test
        owner: cocard
        lc_collate: de_DE.UTF-8
        lc_ctype: de_DE.UTF-8

  roles:
    - role: geerlingguy.postgresql
      become: yes
